<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="122278" started-at="2017-11-15T06:08:44Z" finished-at="2017-11-15T06:10:46Z">
    <groups>
    </groups>
    <test name="TestDebug" duration-ms="122278" started-at="2017-11-15T06:08:44Z" finished-at="2017-11-15T06:10:46Z">
      <class name="me.ele.opensite.test.checkout.CheckOut">
        <test-method status="PASS" signature="setUp()[pri:0, instance:me.ele.opensite.test.checkout.CheckOut@7d78f3d5]" name="setUp" is-config="true" duration-ms="4618" started-at="2017-11-15T14:08:45Z" finished-at="2017-11-15T14:08:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testCheckOut(java.util.Map)[pri:0, instance:me.ele.opensite.test.checkout.CheckOut@7d78f3d5]" name="testCheckOut" duration-ms="116466" started-at="2017-11-15T14:08:49Z" data-provider="providerMethod" finished-at="2017-11-15T14:10:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{baseurl=http://h5-vip.faas.ele.me/msite, keywords=跃进农场, shopName=第三方小程序, url=http://h5-vip.faas.ele.me/msite}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at me.ele.opensite.test.home.SearchRestaurant.testSearch(SearchRestaurant.java:55)
	at me.ele.opensite.test.checkout.CheckOut.testCheckOut(CheckOut.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheckOut -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:me.ele.opensite.test.checkout.CheckOut@7d78f3d5]" name="tearDown" is-config="true" duration-ms="399" started-at="2017-11-15T14:10:46Z" finished-at="2017-11-15T14:10:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- me.ele.opensite.test.checkout.CheckOut -->
    </test> <!-- TestDebug -->
  </suite> <!-- Suite -->
</testng-results>
